import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const source=readFileSync('CONTENT.md','utf8');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function groups(start,end){const body=source.split(start)[1].split(end)[0];return body.split(/^### /m).slice(1).map(chunk=>{const [name,...lines]=chunk.split('\n');return{name:name.trim(),items:lines.filter(l=>l.startsWith('- ')).map(l=>{const parts=l.slice(2).split(' — ');return{name:parts[0],description:parts.length>2?parts.slice(1,-1).join(' · '):'',price:parts.at(-1)}})}})}
const food=groups('## Food menu','## Drinks'),drinks=groups('## Drinks','## Location');
const dishes=items=>'<div class="dish-grid">'+items.map(item=>`<article class="dish"><div><h4>${escape(item.name)}</h4>${item.description?`<p>${escape(item.description)}</p>`:''}</div><span class="price">${escape(item.price)}</span></article>`).join('')+'</div>';
const gallery=[['08-8.jpeg','Seaside tables','Blue glassware and white flowers on a table beside the sea'],['04-4.jpeg','A table with a view','A dressed table looking out onto the blue Mediterranean'],['02-2.jpeg','Thursday, together','Traditional Greek dancer performing among guests'],['06-6.jpeg','The little details','Turquoise candles, flowers and blue glasses on the terrace'],['11-11.jpeg','An occasion to remember','Flower-decorated celebration tables at sunset'],['12-12.jpeg','Room for your people','Terrace tables set with turquoise plates and flowers'],['03-3.jpeg','A little Greek Night magic','A performer balancing glasses at Greek Night'],['13-hero.jpeg','The last light','Sunset reflected in the sea at Argaka']];
let html=readFileSync('index.template.html','utf8').replace('{{MENU_NAV}}',food.map((g,i)=>`<a href="#food-${i}">${escape(g.name)}</a>`).join('')).replace('{{FOOD_MENU}}',food.map((g,i)=>`<section class="menu-panel" id="food-${i}"><h3>${escape(g.name)}</h3>${dishes(g.items)}</section>`).join('')).replace('{{DRINKS}}',drinks.map(g=>`<details><summary>${escape(g.name)}</summary>${dishes(g.items)}</details>`).join('')).replace('{{GALLERY}}',gallery.map(([file,caption,alt])=>`<figure><img src="assets/${file}" loading="lazy" width="1200" height="1600" alt="${escape(alt)}"><figcaption>${escape(caption)}</figcaption></figure>`).join('')).replace('{{HOURS}}',['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(d=>`<tr><td>${d}</td><td>${d==='Tuesday'?'Closed':'12:00 – 22:00'}</td></tr>`).join(''));
if(html.includes('{{'))throw Error('Unresolved template token');
const between=(start,end)=>html.slice(html.indexOf(start),html.indexOf(end));
const home=between(' <section class="hero"',' <section class="menu-section');
const menu=between(' <section class="menu-section',' <section class="night"');
const night=between(' <section class="night"',' <section class="gallery-section');
const setting=between(' <section class="gallery-section',' <section class="values');
const values=between(' <section class="values',' <section class="visit');
const visit=between(' <section class="visit','</main>');
const reviewsURL='https://www.google.com/maps/place/Pas+To+Kima/@35.0684701,32.471571,17z/data=!3m1!4b1!4m6!3m5!1s0x14e771884d2d36c7:0x8c3ef53af8913160!8m2!3d35.0684701!4d32.471571!16s%2Fg%2F11h6r2wtrc';
const testimonials=`<section class="testimonials section" aria-labelledby="reviews-title"><div class="section-top"><div><p class="eyebrow">FROM GOOGLE MAPS</p><h2 id="reviews-title">Good times.<br><em>Kind words.</em></h2></div><div class="review-score"><span class="google-source">Google reviews</span><strong>353</strong><span>353 five-star reviews</span><a class="underlined" href="${reviewsURL}" target="_blank" rel="noopener noreferrer">Read reviews on Google</a></div></div><div class="testimonial-grid">${[['Alison Sullivan','The buffet was plentiful and varied.'],['Osiris Nicolaou','it never disappoints.'],['Chloe Stylianaki','A must if you are in Cyprus!!!']].map(([name,quote])=>`<figure class="google-review"><figcaption class="review-person"><span class="review-avatar" aria-hidden="true">${name.split(' ').map(x=>x[0]).join('')}</span><span>${name}<small>Google review · excerpt</small></span></figcaption><div class="review-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“${quote}”</blockquote><a class="review-original" href="${reviewsURL}" target="_blank" rel="noopener noreferrer">View restaurant reviews on Google</a></figure>`).join('')}</div><div class="review-source"><p>Selected excerpts from public Google Maps reviews. Rating snapshot checked 17 September 2026; not a live feed.</p></div></section>`;
const explore=`<section class="explore section"><p class="eyebrow">MAKE AN EVENING OF IT</p><div class="explore-grid"><a href="/menu/"><span>01 / THE MENU</span><h2>A taste of<br><em>the Mediterranean.</em></h2><p>Explore our food &amp; drinks ↗</p></a><a href="/greek-night/"><span>02 / THURSDAY GREEK NIGHT</span><h2>A little music.<br><em>A lot of kefi.</em></h2><p>See what Thursdays look like ↗</p></a></div></section>`;
const map=`<section class="map-section section" aria-labelledby="map-title"><div class="section-top"><div><p class="eyebrow">YOUR WAY TO THE WAVE</p><h2 id="map-title">Find us in <em>Argaka.</em></h2></div><a class="underlined" href="${reviewsURL}" target="_blank" rel="noopener">Open in Google Maps ↗</a></div><iframe title="Map showing Pas To Kima in Argaka, Cyprus" src="https://www.google.com/maps?q=Pas%20To%20Kima%2C%20E704%2C%20Argaka%208873%2C%20Cyprus&amp;output=embed" width="1200" height="500" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></section>`;
const promote=content=>content.replace(/<h2([^>]*)>/,'<h1$1>').replace('</h2>','</h1>');
const pages=[['','Mediterranean cooking, Cypriot heart',home+explore+testimonials+values],['menu','Food & drinks menu',promote(menu)],['greek-night','Thursday Greek Night',promote(night)],['gallery','The setting',promote(setting)],['contact','Visit & contact',promote(visit)+map]];
for(const [slug,title,body] of pages){
 let page=html.slice(0,html.indexOf('<main id="main">'))+`<main id="main" class="${slug?'inner-page':'home-page'}">`+body+html.slice(html.indexOf('</main>'));
 page=page.replace(/<title>.*?<\/title>/,`<title>Pas To Kima · ${title}</title>`).replace('href="#menu">The menu','href="#top">Home</a><a href="#menu">The menu');
 for(const [anchor,path] of Object.entries({top:'/',menu:'/menu/','greek-night':'/greek-night/',gallery:'/gallery/',visit:'/contact/'}))page=page.replaceAll(`href="#${anchor}"`,`href="${path}"`);
 page=page.replace('>Find us</a>','>Visit &amp; Contact</a>').replaceAll('="assets/','="/assets/').replaceAll('href="scrollcraft.css"','href="/scrollcraft.css"').replaceAll('href="style.css"','href="/style.css"').replaceAll('src="scrollcraft.js"','src="/scrollcraft.js"').replaceAll('src="app.js"','src="/app.js"');
 const path=slug?`/${slug}/`:'/';
 page=page.replaceAll('Google review · excerpt','Google Maps');
 const icons={Instagram:'<rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="18" cy="6" r="1.2"/>',Facebook:'<path d="M24 12.073C24 5.405 18.627 0 12 0S0 5.405 0 12.073C0 18.1 4.388 23.094 10.125 24v-8.437H7.078v-3.49h3.047V9.413c0-3.026 1.792-4.697 4.533-4.697 1.312 0 2.686.236 2.686.236v2.97H15.83c-1.49 0-1.955.931-1.955 1.887v2.264h3.328l-.532 3.49h-2.796V24C19.612 23.094 24 18.1 24 12.073z"/>',TikTok:'<path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.8-1.35 3.95-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.72-.02-.5-.03-1-.01-1.49.18-1.91 1.13-3.74 2.61-4.98 1.68-1.46 4.03-2.16 6.22-1.75.02 1.48-.04 2.96-.04 4.44-1-.32-2.17-.23-3.04.38-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.81 3.02 3.49 2.87 1.11-.01 2.17-.65 2.75-1.59.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.02-.01-8.03.02-12.05z"/>'};
 for(const [name,shape] of Object.entries(icons))page=page.replace(`${name} ↗</a>`,`<svg class="social-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${shape}</svg><span>${name}</span></a>`);
 page=page.replaceAll('↗','<span class="link-arrow" aria-hidden="true">↗</span>').replace('>←</button>','><span class="desktop-arrow" aria-hidden="true">←</span><span class="mobile-control-label">Previous</span></button>').replace('>→</button>','><span class="desktop-arrow" aria-hidden="true">→</span><span class="mobile-control-label">Next</span></button>');
 page=page.replace(/(<nav aria-label="Main navigation">)(.*?)(<\/nav>)/,(_,a,links,c)=>a+links.replace(`href="${path}"`,`aria-current="page" href="${path}"`)+c);
 mkdirSync(`dist/${slug}`,{recursive:true});writeFileSync(`dist/${slug?slug+'/':''}index.html`,page);
}
console.log(JSON.stringify({foodCategories:food.length,foodItems:food.reduce((n,g)=>n+g.items.length,0),drinksCategories:drinks.length,drinksItems:drinks.reduce((n,g)=>n+g.items.length,0)}));
