import {apiRequest} from './auth.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
let state,activeView='assistant',pending,uploadURL;
// Add the description beside the file picker so changed images stay accessible.
const altLabel=document.createElement('label');altLabel.id='media-alt-label';altLabel.textContent='Describe the replacement photo';const altInput=document.createElement('input');altInput.id='media-alt';altInput.maxLength=250;altLabel.append(altInput);$('#media-file').after(altLabel);
const titles={assistant:'Your assistant',menu:'Menu & prices',media:'Photos & video',details:'Restaurant details',history:'History & backup',privacy:'Privacy & access'};
function status(message,error=false){$('#status').textContent=message;$('#status').className=error?'error':'success';}
const api=apiRequest;
const mediaPreviews=new Map();
async function task(button,fn){if(button)button.disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{if(button)button.disabled=false;}}
async function reload(){state=await api('state');$('#account-line').textContent=`${state.email} · Content revision ${state.revision}`;$('#access-summary').textContent=`You are signed in as ${state.email}. Additional restaurant owners must be explicitly added by the site administrator.`;$('#ai-option').hidden=!state.aiEnabled;$('#assistant-mode').textContent=state.aiEnabled?'Guided commands by default. External AI sends this request to OpenAI when selected.':'Guided commands · no external AI connected · chat text is not saved';if(!state.writeEnabled)status('Editing is locked by the site administrator.',true);renderMenu();renderDetails();renderSlots();}
async function view(name){activeView=name;$$('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==name);$$('[data-view]').forEach(x=>{if(x.dataset.view===name)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});$('#view-title').textContent=titles[name];if(name==='history')await renderHistory();if(name==='media')await renderLibrary();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>task(b,()=>view(b.dataset.view))));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>task(b,()=>view(b.dataset.go))));
$$('[data-example]').forEach(b=>b.addEventListener('click',()=>{$('#chat-input').value=b.dataset.example;$('#chat-input').focus();}));
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();task(e.submitter,async()=>{const result=await api('assistant',{message:$('#chat-input').value,revision:state.revision,mode:$('#use-ai').checked?'ai':'guided'});if(result.id)review(result);else $('#chat-result').textContent=result.message;});});
function mediaMarkup(url,type,alt=''){url=mediaPreviews.get(url)||(url.startsWith('/media/')?state.mediaBase+url.slice(7):url);return type==='video'?`<video src="${esc(url)}" controls preload="metadata" aria-label="${esc(alt)}"></video>`:`<img src="${esc(url)}" alt="${esc(alt)}" loading="lazy">`;}
function review(proposal){
 pending=proposal;$('#review-summary').textContent=proposal.summary;$('#review-error').textContent='';$('#publish').disabled=false;
 $('#review-changes').innerHTML=proposal.changes.map(c=>`<div class="change-row"><h3>${esc(c.label)}</h3><div class="comparison"><div><small>CURRENT</small>${['image','video'].includes(c.type)?mediaMarkup(c.before,c.type,'Current '+c.label):esc(c.before||'(empty)')}</div><div><small>PROPOSED</small>${['image','video'].includes(c.type)?mediaMarkup(c.after,c.type,'Proposed '+c.label):esc(c.after||'(empty)')}</div></div></div>`).join('');
 $$('[data-preview]').forEach(a=>{a.href='#';a.onclick=e=>{e.preventDefault();const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;task(null,async()=>{try{const result=await api('preview',{id:proposal.id,page:a.dataset.preview});const blob=URL.createObjectURL(new Blob([result.html],{type:'text/html'}));if(tab)tab.location=blob;setTimeout(()=>URL.revokeObjectURL(blob),60000);}catch(error){if(tab)tab.close();throw error;}});};});$('#review-dialog').showModal();
}
async function cancelReview(){const id=pending?.id;pending=null;$('#review-dialog').close();if(id)try{await api('cancel',{id});}catch{status('The unused preview will expire automatically in 10 minutes.');}}
$('#close-review').addEventListener('click',cancelReview);$('#cancel-review').addEventListener('click',cancelReview);$('#review-dialog').addEventListener('cancel',e=>{e.preventDefault();cancelReview();});
$('#publish').addEventListener('click',async()=>{if(!pending)return;$('#publish').disabled=true;try{const result=await api('publish',{id:pending.id,confirm:true});pending=null;$('#review-dialog').close();await reload();await view(activeView);status(result.message);$('#chat-result').textContent=result.message;}catch(e){$('#review-error').textContent=e.message;$('#publish').disabled=false;}});
function renderMenu(){
 const term=$('#menu-search').value.toLowerCase();let lastCategory='';$('#menu-list').innerHTML=state.menu.filter(x=>(state.values[x.id+'.name']+' '+x.category).toLowerCase().includes(term)).map(item=>{const category=item.kind+' / '+item.category;let heading='';if(category!==lastCategory){lastCategory=category;heading=`<h2 class="menu-category">${esc(item.category)}</h2>`;}return heading+`<article class="menu-row"><div><strong>${esc(state.values[item.id+'.name'])}</strong><p>${esc(state.values[item.id+'.description'])}</p>${state.values[item.id+'.visible']==='no'?'<p>Hidden from menu</p>':''}</div><span class="price">${esc(state.values[item.id+'.price'])}</span><button data-edit="${item.id}" class="secondary">Edit</button></article>`;}).join('')||'<p>No matching items.</p>';
 $$('[data-edit]').forEach(b=>b.addEventListener('click',()=>editDish(b.dataset.edit)));
}
$('#menu-search').addEventListener('input',()=>state&&renderMenu());
function editDish(id){
 const dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Edit menu item');dialog.innerHTML=`<form class="edit-form"><h2>Edit menu item</h2><label>Name<input name="name" maxlength="150" required value="${esc(state.values[id+'.name'])}"></label><label>Description<textarea name="description" maxlength="800">${esc(state.values[id+'.description'])}</textarea></label><label>Price in euros<input name="price" inputmode="decimal" required value="${esc(state.values[id+'.price'].replace('€',''))}"></label><label>Availability<select name="visible"><option value="yes">Show on menu</option><option value="no">Hide for now</option></select></label><p class="small">Check ingredients and allergen information before publishing.</p><p class="edit-error" role="alert"></p><div class="dialog-actions"><button type="button" class="secondary close-edit">Cancel</button><button class="primary" type="submit">Review change</button></div></form>`;
 document.body.append(dialog);dialog.querySelector('select').value=state.values[id+'.visible'];dialog.querySelector('.close-edit').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const data=new FormData(e.target);const patch=[...data].map(([key,value])=>({key:id+'.'+key,value})).filter(p=>p.value!==state.values[p.key]);const p=await api('propose',{revision:state.revision,patch});dialog.close();review(p);}catch(error){dialog.querySelector('.edit-error').textContent=error.message;e.submitter.disabled=false;}};dialog.showModal();
}
function renderDetails(){
 for(const [section,selector] of [['details','#detail-fields'],['hours','#hour-fields']])$(selector).innerHTML=Object.entries(state.schema).filter(([,f])=>f.section===section).map(([key,f])=>`<label class="${f.max>500?'full':''}">${esc(f.label)}${f.max>250?`<textarea data-field="${key}" maxlength="${f.max}" rows="3">${esc(state.values[key])}</textarea>`:`<input data-field="${key}" value="${esc(state.values[key])}" maxlength="${f.max}" required>`}</label>`).join('');
}
$('#details-form').addEventListener('submit',e=>{e.preventDefault();task(e.submitter,async()=>{const patch=$$('[data-field]').filter(x=>x.value!==state.values[x.dataset.field]).map(x=>({key:x.dataset.field,value:x.value}));review(await api('propose',{revision:state.revision,patch}));});});
function renderSlots(){const before=$('#media-slot').value;$('#media-slot').innerHTML=Object.entries(state.schema).filter(([,f])=>f.section==='media').map(([k,f])=>`<option value="${k}">${esc(f.label)}</option>`).join('');if(before)$('#media-slot').value=before;showSlot();}
function showSlot(){const key=$('#media-slot').value,field=state.schema[key];$('#current-media').innerHTML=mediaMarkup(state.values[key],field.type,'Current '+field.label);$('#media-file').accept=field.type==='video'?'video/mp4':'image/jpeg,image/png,image/webp';$('#media-file').value='';$('#media-rights').checked=false;$('#upload-preview').replaceChildren();if(uploadURL)URL.revokeObjectURL(uploadURL);const altKey=key.replace('media.','alt.');$('#media-alt-label').hidden=field.type==='video';$('#media-alt').required=field.type!=='video';$('#media-alt').value=state.values[altKey]||'';}
$('#media-slot').addEventListener('change',showSlot);
$('#media-file').addEventListener('change',()=>{const file=$('#media-file').files[0];if(uploadURL)URL.revokeObjectURL(uploadURL);if(!file)return;uploadURL=URL.createObjectURL(file);$('#upload-preview').innerHTML=mediaMarkup(uploadURL,file.type.startsWith('video/')?'video':'image','Selected replacement');});
async function photoBlob(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw new Error('Choose a JPEG, PNG or WebP photo under 15 MB.');
 const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>50000000){bitmap.close();throw new Error('This image is too large. Resize it before uploading.');}
 const ratio=Math.min(1,2400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);const context=canvas.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not prepare this photo.')),'image/jpeg',.88));
}
$('#media-form').addEventListener('submit',e=>{e.preventDefault();task(e.submitter,async()=>{const key=$('#media-slot').value,file=$('#media-file').files[0];if(!file||!$('#media-rights').checked)throw new Error('Choose a file and confirm publishing permission.');const video=state.schema[key].type==='video';if(video&&(file.type!=='video/mp4'||file.size>20*1024*1024))throw new Error('Choose an MP4 video under 20 MB.');status('Preparing and uploading your file…');const data=video?file:await photoBlob(file);const uploaded=await api('upload',data,{raw:true,headers:{'Content-Type':video?'video/mp4':'image/jpeg','X-Media-Rights':'confirmed'}});await renderLibrary();const patch=[{key,value:uploaded.url}];if(!video)patch.push({key:key.replace('media.','alt.'),value:$('#media-alt').value});review(await api('propose',{revision:state.revision,patch}));status('Upload ready. Review it before publishing.');});});
async function renderLibrary(){
 const files=await api('media');for(const file of files)if(file.previewURL)mediaPreviews.set('/media/'+file.id,file.previewURL);$('#media-library').innerHTML=files.length?files.map(f=>`<div class="media-item">${f.deleted?'':mediaMarkup('/media/'+f.id,f.type==='video/mp4'?'video':'image','Uploaded restaurant media')}<p>${f.type==='video/mp4'?'Video':'Photo'} · ${(f.size/1024/1024).toFixed(1)} MB · ${new Date(f.created*1000).toLocaleDateString()}</p>${f.deleted?'<p>Deletion pending. Retry to remove the stored file.</p>':`<a href="${esc(f.previewURL)}" target="_blank" rel="noopener" download>Open / download</a><br><button class="secondary" data-use="${f.id}" data-type="${f.type}">Use in selected slot</button>`}<button class="danger" data-delete="${f.id}">Delete permanently</button></div>`).join(''):'<p class="small">Your new uploads will appear here.</p>';
 $$('[data-use]').forEach(b=>b.onclick=()=>task(b,async()=>{const key=$('#media-slot').value;if((state.schema[key].type==='video')!==(b.dataset.type==='video/mp4'))throw new Error('Select a matching photo or video slot first.');review(await api('propose',{revision:state.revision,patch:[{key,value:'/media/'+b.dataset.use}]}));}));
 $$('[data-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Permanently delete this uploaded file? It cannot be recovered from content history. Files still in use cannot be deleted.'))return;task(b,async()=>{const r=await api('delete-media',{id:b.dataset.delete,confirm:true});await renderLibrary();status(r.message);});});
}
async function renderHistory(){const rows=await api('history');$('#history-list').innerHTML=rows.map(r=>`<article class="history-row"><div><strong>${esc(r.summary)}</strong><p>Revision ${r.revision} · ${new Date(r.created*1000).toLocaleString()}</p></div>${r.revision===state.revision?'<span class="badge">Current</span>':`<button class="secondary" data-restore="${r.id}">Review restore</button>`}</article>`).join('');$$('[data-restore]').forEach(b=>b.onclick=()=>task(b,async()=>review(await api('restore',{id:Number(b.dataset.restore),revision:state.revision}))));}
$('#export').addEventListener('click',e=>task(e.target,async()=>{const content=await api('export');const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pastokima-content-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Content backup downloaded.');}));
reload().then(()=>status('Ready. Changes are reviewed before publishing.')).catch(e=>status(e.message,true));
